parameters:

services:
    _defaults:
        autowire: true      
        autoconfigure: true 

    Symfony\Component\Security\Http\Authenticator\FormLoginAuthenticator:
        alias: 'security.authenticator.form_login.main'

    App\:
        resource: '../src/*'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']
    App\Command\:
        resource: '../src/Command'
        tags: ['console.command']

    App\Security\EmailVerifier:
        arguments:
            $mailer: '@mailer.mailer'

    App\EventSubscriber\AppGlobalsSubscriber:
        autowire: true
        autoconfigure: true 

    App\Command\TestEmailCommand:
        tags: ['console.command']